import Header from '@/components/Header';
import Head from 'next/head';
import Container from 'react-bootstrap/Container';
import usePosts from '@/hooks/usePosts';
import { useRouter } from 'next/router';
import PostEditForm from '@/components/PostEditForm';
import Alert from 'react-bootstrap/Alert';
import Button from 'react-bootstrap/Button';
import { useState } from 'react';
import Link from 'next/link';

const NewPostPage = () => {
  const router = useRouter();
  const { createPost } = usePosts();
  const [alertMessage, setAlertMessage] = useState<{
    type: string;
    message: string;
  } | null>(null);

  const handleSubmit = async (title: string, body: string) => {
    try {
      const { id } = await createPost(title, body);
      router.push(`/posts/${id}`);
    } catch (error: any) {
      setAlertMessage({ type: 'danger', message: error.message });
    }
  };

  return (
    <>
      <Head>
        <title>Posts list</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
        <Container>
          <Link href="/" legacyBehavior>
            <Button variant="link">{'<'}Back to all posts</Button>
          </Link>

          {alertMessage && (
            <Alert variant={alertMessage.type}>{alertMessage.message}</Alert>
          )}
          <h1>New Post</h1>
          <PostEditForm saveForm={handleSubmit} />
        </Container>
      </main>
    </>
  );
};

export default NewPostPage;
